version: '3.3'
services:
    web:
      image: nginx:latest
      ports:
        - 8199:80
      volumes:
        - ./:/var/www
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

      links:
        - php

    php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
      ports:
        - 9000:9000
      volumes:
        - ./:/var/www
        - ./docker/php/ini/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      working_dir: /var/www

