version: '3.3'
services:
    web:
      image: nginx:latest
      ports:
        - 8199:80
      volumes:
        - ./:/var/www
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        - ./php/ini:/usr/local/etc/php
      links:
        - php

    php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
      ports:
        - 9000:9000
      volumes:
        - ./:/var/www
      links:
        - db
      working_dir: /var/www

    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: my_secret_pw_shh
        MYSQL_DATABASE: test_db
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - "9906:3306"
